set(CMAKE_SYSTEM_NAME MorphOS)

set(CMAKE_C_COMPILER ppc-morphos-gcc-12)
set(CMAKE_C_FLAGS "-noixemul")
set(CMAKE_CXX_COMPILER ppc-morphos-g++-12)
set(CMAKE_CXX_FLAGS "-noixemul")
set(CMAKE_EXE_LINKER_FLAGS "-noixemul")

set(CMAKE_FIND_ROOT_PATH /gg)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

set(CMAKE_FIND_LIBRARY_PREFIXES "lib")
set(CMAKE_FIND_LIBRARY_SUFFIXES ".a")

set(CMAKE_CXX_IMPLICIT_INCLUDE_DIRECTORIES /gg/os-include)
